# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Polyglot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Polyglot
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftSoup'

  target 'PolyglotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PolyglotUITests' do
    # Pods for testing
  end

end
